Add metadata to create .cab files for the LVFS
Logitech/fw_updates pull request #3
Opened 2017-05-03 10:36 UTC by hughsie

This will create files of the format Logitech-Unifying-RQR024.005_B00029.cab

Signed-off-by: Richard Hughes <richard@hughsie.com>

2017-05-05 10:35 UTC, ogay commented on RQR12/RQR12.05/com.logitech.Unifying.RQR12.metainfo.xml
> +      <checksum filename="RQR12.07_B0029.hex" target="content"/>
RQR12.05_B0028 ?

2017-05-05 16:26 UTC, hughsie commented on RQR12/RQR12.05/com.logitech.Unifying.RQR12.metainfo.xml
> +      <checksum filename="RQR12.07_B0029.hex" target="content"/>
Good catch, will respin now.

2017-05-08 10:41 UTC, ogay commented
We discussed it and we would prefer if every Makefile and xml file comes in its own folder, called 'lvfs', e.g., 

RQR12/RQR12.07/RQR12.07_B0029.hex
RQR12/RQR12.07/RQR12.07_B0029.txt
RQR12/RQR12.07/lvfs/com.logitech.Unifying.RQR12.metainfo.xml
RQR12/RQR12.07/lvfs/Makefile

and the Makefile would create the .cab in the same level as the level of the Makefile: i.e., 
RQR12/RQR12.07/lvfs/Logitech-Unifying-RQR12.07_B0029.cab

2017-05-08 11:35 UTC, hughsie commented
As you wish; one sec.

2017-05-08 13:19 UTC, ogay requested changes
Sorry I didn't catch this during the last review.

The cab filenames have an inconsistent format; the RQR12 are the correct one.

It also appears in the commit message:
Logitech-Unifying-RQR024.005_B00029.cab should be Logitech-Unifying-RQR24.05_B0029.cab (three extra 0s)

2017-05-08 13:19 UTC, ogay commented on RQR24/RQR24.03/lvfs/Makefile
> +VERSION=RQR024.003_B00027
VERSION=RQR24.03_B0027
(there were three extra 0s)

2017-05-08 13:19 UTC, ogay commented on RQR24/RQR24.05/lvfs/Makefile
> +VERSION=RQR024.005_B00029
VERSION=RQR24.05_B0029
(there were three extra 0s)

2017-05-08 15:33 UTC, hughsie commented
My error entirely, sorry. New version pushed.

2017-05-08 18:53 UTC, merged